# Generated by Django 5.0.6 on 2024-07-01 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_type', models.CharField(choices=[('AO', 'AO'), ('CEO', 'CEO'), ('OB', 'OB'), ('MC', 'MC'), ('GC', 'GC')], default='AO', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameofApplicant', models.CharField(default=None, max_length=255, null=True, verbose_name='Name of Applicant')),
                ('constitution', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Proprietory Firm', 'Proprietory Firm'), ('Partnership Firm LLP', 'Partnership Firm LLP'), ('Private Limited', 'Private Limited'), ('Public Limited Unlisted', 'Public Limited Unlisted'), ('Public Limited Listed', 'Public Limited Listed'), ('Trust', 'Trust'), ('Society', 'Society'), ('Associations', 'Associations')], max_length=50, null=True, verbose_name='Constitution')),
                ('profession1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession 1')),
                ('profession2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession 2')),
                ('profession3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession 3')),
                ('YearofEstablishment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Year of Establishment')),
                ('Businessactivity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Activity')),
                ('Registerofficeaddress', models.TextField(blank=True, null=True, verbose_name='Registered Office Address')),
                ('Addressforcommunication_office', models.TextField(blank=True, null=True, verbose_name='Office Address for Communication')),
                ('Addressforcommunication_work', models.TextField(blank=True, null=True, verbose_name='Work Address for Communication')),
                ('Communicationdetails_landline', models.CharField(blank=True, max_length=20, null=True, verbose_name='Landline Number')),
                ('Communicationdetails_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('Communicationdetails_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('Communicationdetails_web', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('Legalinfo_aadhar', models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhar Number')),
                ('Legalinfo_pancard', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Card Number')),
                ('Legalinfo_GSTNo', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number')),
                ('Legalinfo_CompanyFirmRegNo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Company/Firm Registration Number')),
                ('Legalinfo_SocietyAssociationRegNo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Society/Association Registration Number')),
                ('Personauthorized_Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authorized Person Name')),
                ('Personauthorized_Designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authorized Person Designation')),
                ('personauthorized_pan', models.CharField(blank=True, max_length=10, null=True, verbose_name='Authorized Person PAN Number')),
                ('personauthorized_aadhar', models.CharField(blank=True, max_length=12, null=True, verbose_name='Authorized Person Aadhar Number')),
                ('personauthorized_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Authorized Person Phone Number')),
                ('personauthorized_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Authorized Person Email Address')),
                ('Maincategory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Main Category')),
                ('Subcategory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subcategory')),
                ('Cateringtomarket', models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('Global', 'Global'), ('Both', 'Both')], max_length=50, null=True, verbose_name='Catering to Market')),
                ('Percentageofimports', models.CharField(blank=True, max_length=10, null=True, verbose_name='Percentage of Imports')),
                ('Percentageofexports', models.CharField(blank=True, max_length=10, null=True, verbose_name='Percentage of Exports')),
                ('Foreigncollaboration_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country of Foreign Collaboration')),
                ('Foreigncollaboration_collaborator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Collaborator Name')),
                ('Classificationofindustry', models.CharField(blank=True, choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('Micro', 'Micro')], max_length=50, null=True, verbose_name='Classification of Industry')),
                ('Annualturnover_year1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Annual Turnover Year 1')),
                ('Annualturnover_year2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Annual Turnover Year 2')),
                ('Annualturnover_year3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Annual Turnover Year 3')),
                ('Noofpersonsemployed_direct', models.BigIntegerField(blank=True, null=True, verbose_name='Number of Persons Employed Directly')),
                ('Noofpersonsemployed_works', models.BigIntegerField(blank=True, null=True, verbose_name='Number of Workers Employed')),
                ('Noofpersonsemployed_indirect', models.BigIntegerField(blank=True, null=True, verbose_name='Number of Indirect Employees')),
                ('Noofpersonsemployed_outsourced', models.BigIntegerField(blank=True, null=True, verbose_name='Number of Outsourced Employees')),
                ('ESIC', models.CharField(blank=True, max_length=255, null=True, verbose_name='ESIC Compliance')),
                ('EPF', models.CharField(blank=True, max_length=255, null=True, verbose_name='EPF Compliance')),
                ('Detailsofbranches', models.TextField(blank=True, null=True, verbose_name='Details of Branches')),
                ('Memberofanyother', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True, verbose_name='Member in Other Association')),
                ('association_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Association Name')),
                ('is_office_bearer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True, verbose_name='Office Bearer in Association')),
                ('association_position', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Association Position')),
                ('reason_for_joining_chamber', models.TextField(default=None, null=True, verbose_name='Reason for Joining the Chamber')),
                ('e_sign', models.FileField(null=True, upload_to='e_sign/', verbose_name='E-Signature')),
                ('IncomeandExpenditure', models.FileField(null=True, upload_to='incomeandexpenditure/', verbose_name='Income and Expenditure Statement')),
                ('incometaxtpan', models.FileField(null=True, upload_to='incometaxtpan/', verbose_name='Income Tax PAN Copy')),
                ('FactoryRegistrationCertificate', models.FileField(null=True, upload_to='FactoryRegistrationCertificate/', verbose_name='Factory Registration Certificate')),
                ('MemorandumArticleofAssociation', models.FileField(null=True, upload_to='MemorandumArticleofAssociation/', verbose_name='Memorandum and Articles of Association')),
                ('GSTINRegistrationCopy', models.FileField(null=True, upload_to='GSTINRegistrationCopy/', verbose_name='GSTIN Registration Copy')),
                ('IECodeCertificate', models.FileField(null=True, upload_to='IECodeCertificate/', verbose_name='IEC Code Certificate')),
                ('ProfessionalCertificate', models.FileField(null=True, upload_to='ProfessionalCertificate/', verbose_name='Professional Certificate')),
                ('CopyofLandDocument', models.FileField(null=True, upload_to='CopyofLandDocument/', verbose_name='Copy of Land Document')),
                ('LandHolding', models.FileField(null=True, upload_to='LandHolding/', verbose_name='Land Holding')),
                ('passportsizephoto', models.FileField(null=True, upload_to='passportsizephoto/', verbose_name='Passport Size Photo')),
                ('DirectorsPartners', models.FileField(null=True, upload_to='Direct1orsPartners/', verbose_name='Details of Directors/Partners')),
                ('form_status', models.CharField(choices=[('pending', 'Pending'), ('Approved by AO', 'Approved by AO'), ('Approved by CEO', 'Approved by CEO'), ('Approved by Membership Committee', 'Approved by Membership Committee'), ('Approved by OB', 'Approved by OB'), ('waiting for payment', 'Waiting for Payment'), ('payment done (approved as Member)', 'Payment Done (Approved as Member)'), ('rejected', 'Rejected')], default='pending', max_length=50, verbose_name='Form Status')),
                ('Reasonforrejection', models.TextField(blank=True, default=None, null=True, verbose_name='Reason for Rejection')),
                ('approved_by', models.ManyToManyField(blank=True, related_name='approved_forms', to='app.adminuser')),
            ],
        ),
    ]
