# Generated by Django 5.0.6 on 2024-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_forms', to='app.adminuser'),
        ),
    ]
